name: Run CFP Simulation

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      N:
        type: choice
        description: 'Number of simulations to run:'
        default: '2000'
        required: true
        options: 
          - '2000'
          - '1000'
          - '100'
      AQ:
        type: choice
        description: 'Number of automatic qualifiers:'
        default: '6'
        required: true
        options:
          - '6'
          - '5'
      PLAYOFF:
        description: 'Number of teams that make the playoffs:'
        default: '12'
        required: true

jobs:

  run_sim:
    name: Run Simulation
    runs-on: ubuntu-latest
    steps:

    # access the repository
    - name: Checkout repo content
      uses: actions/checkout@v2

    # setup python to run the simulation
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Install packages
      run: pip install -r ./.github/workflows/requirements.txt

    # run the python script to create the CSVs
    - name: Run simulation script
      run: python main.py

    # commit the CSVs to the repository
    - name: Commit output tables
      run: |-
        git config user.name "Actions User"
        git config user.email "actions@users.noreply.github.com"
        git add - A
        git commit -am "Load Sim Results $(date)"
        git push

