name: Run CFP Simulation

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      N:
        description: 'Number of simulations to run:'
        default: '2000'
        required: true
        options: 
          - '2000'
          - '1000'
          - '100'
      AQ:
        description: 'Number of automatic qualifiers:'
        required: true
        options:
          - '6'
          - '5'
      PLAYOFF:
        description: 'Number of teams that make the playoffs:'
        default: '12'
        required: true

jobs:

  run_sim:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ inputs.name }}"
